# Generated by Django 4.1.3 on 2022-11-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_test_remove_habit_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
