# Generated by Django 4.1.3 on 2022-11-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0004_dailyrecord_delete_record_remove_habit_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
