# Generated by Django 4.1.3 on 2022-11-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0007_rename_name_habit_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
    ]
