# Generated by Django 4.1.3 on 2022-11-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0010_rename_action_habit_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'completed_date'), name='unique_daily_record'),
        ),
    ]
